import madison from "./images/logos/madison.png";
import aar from "./images/logos/aar.png";
import icea from "./images/logos/icea.png";
import apa from "./images/logos/apa.png";
import cic from "./images/logos/cic.png";

export const ntsa_car_data = [
  {
    no_plate: "KCA 001A",
    make: "Toyota",
    model: "Corolla",
    year: "2014",
    fuel: "Petrol",
    engine: "2000 CC",
    value: 1000000,
  },
  {
    no_plate: "KBH 123A",
    make: "Mercedes Benz",
    model: "C200",
    year: "2008",
    fuel: "Petrol",
    engine: "2000 CC",
    value: 2300000,
  },
  {
    no_plate: "KBD 345R",
    make: "Subaru",
    model: "Forester",
    year: "2011",
    fuel: "Petrol",
    engine: "2500 CC",
    value: 1300000,
  },
  {
    no_plate: "KCZ 218U",
    make: "Suzuki",
    model: "Swift",
    year: "2015",
    fuel: "Petrol",
    engine: "1200 CC",
    value: 600000,
  },
  {
    no_plate: "KBY 123A",
    make: "Mitsubishi",
    model: "Shogun",
    year: "2015",
    fuel: "Petrol",
    engine: "3800 CC",
    value: 1500000,
  },
];

export const car_make = [
  { id: 1, name: "Mercedes" },
  { id: 2, name: "Toyota" },
  { id: 3, name: "Subaru" },
  { id: 4, name: "Volkswagen" },
  { id: 5, name: "Tata" },
  { id: 6, name: "Honda" },
  { id: 7, name: "Hyundai" },
  { id: 8, name: "Volvo" },
  { id: 9, name: "Nissan" },
  { id: 10, name: "Land Rover" },
  { id: 11, name: "Mitsubishi" },
  { id: 12, name: "Mazda" },
  { id: 13, name: "Isuzu" },
  { id: 14, name: "Ford" },
  { id: 15, name: "Suzuki" },
];

export const car_models = [
  {
    id: 1,
    models: [
      {
        name: "C200",
        year: "2015",
        engine: "3800 CC",
        estimated_value: 2500000,
      },
      {
        name: "E350",
        year: "2015",
        engine: "2000 CC",
        estimated_value: 2500000,
      },
      {
        name: "C180",
        year: "2015",
        engine: "2000 CC",
        estimated_value: 1500000,
      },
      {
        name: "C63",
        year: "2015",
        engine: "2000 CC",
        estimated_value: 1500000,
      },
    ],
  },
];

export const plans = [
  {
    name: "Motor Best Plan",
    best_value: false,
    excess: 0.0045,
    pvt: 0.004,
    phcf: 0.0025,

    code: "abcd",
    logo: aar,
    company: "aar",
    levy: 40,
  },
  {
    name: "Comprehensive Best Plan",
    best_value: true,
    excess: 0.0055,
    pvt: 0.004,
    phcf: 0.0025,
    code: "efgh",
    logo: aar,
    company: "aar",
    levy: 40,
  },
  {
    name: "Third party and Fire",
    best_value: false,
    excess: 0.006,
    pvt: 0.003,
    phcf: 0.0025,
    code: "ijkl",
    logo: madison,
    company: "madison",
    levy: 40,
  },
  {
    name: "Vehicle Plan Select",
    best_value: false,
    excess: 0.004,
    pvt: 0.004,
    phcf: 0.0025,
    code: "mnop",
    logo: apa,
    company: "apa",
    levy: 40,
  },
  {
    name: "Motor Best Plan",
    best_value: true,
    excess: 0.0048,
    pvt: 0.005,
    phcf: 0.0025,
    code: "qrst",
    logo: icea,
    company: "icea",
    levy: 40,
  },
  {
    name: "Motor Best Plan",
    best_value: false,
    excess: 0.0092,
    pvt: 0.009,
    phcf: 0.0025,
    code: "uvwx",
    logo: madison,
    company: "madison",
    levy: 40,
  },
  {
    name: "Vehicle Plan Select",
    best_value: false,
    excess: 0.019,
    pvt: 0.004,
    phcf: 0.0025,
    code: "z1ab",
    logo: apa,
    company: "apa",
    levy: 40,
  },
  {
    name: "Motor Best Plan",
    best_value: true,
    excess: 0.0012,
    pvt: 0.005,
    phcf: 0.0025,
    code: "2cde",
    logo: cic,
    company: "cic",
    levy: 40,
  },
  {
    name: "Motor Best Plan",
    best_value: false,
    excess: 0.0032,
    pvt: 0.006,
    phcf: 0.0025,
    code: "3fgh",
    logo: aar,
    company: "aar",
    levy: 40,
  },
];
